-- sync-plans.sql
-- Deprecated for Deekshant (21 Aug 2026).
-- Live plans: Supabase daily_plans (source of truth).
-- Do not paste old HM peak/taper UPDATEs here.
-- Namrata: generate via
--   python3 seed-plans.py --plans athletes/namrata/coach/week-plans.py --sql-only
